backend:
  name: git-gateway
  branch: main

  media_folder: "src/assets/images"
  public_folder: ""

  publish_mode: editorial_workflow

collections:
  - name: "post"
    label: "Blog Post"
    folder: "src/content/blog"
    media_folder: "src/assets/images"
    format: "mdx"
    create: true
    fields:
      - label: "Cover Image"
        name: "heroImage"
        widget: "image"
        required: true
        hint: "The image used for the cover of the post"

      - label: "Category"
        name: "category"
        widget: "select"
        required: true
        hint: "Select a category for this post"
        options:
          - "CATEGORY1" # Replace with actual categories
          - "CATEGORY2" # Replace with actual categories

      - label: "Description"
        name: "description"
        widget: "string"
        required: true
        hint: "A short description of the post"

      - label: "Publication Date"
        name: "pubDate"
        widget: "datetime"
        required: true

      - label: "Draft"
        name: "draft"
        widget: "boolean"
        hint: "If this is checked, the post will not be published"

      - label: "Tags"
        name: "tags"
        widget: "list"
        required: true
        hint: "Tags for this post"
        field:
          widget: "string"

      - label: "Title"
        name: "title"
        widget: "string"
        required: true
        isTitle: true

      - label: "Body"
        name: "SButton"
        widget: "markdown"
        required: true
        hint: "Main content of the post"
        fields:
          - label: "SButton"
            name: "children"
            widget: "markdown"
            required: true
